// FIFA World Cup 2026 - Group Stage schedule (Draw: Dec 5, 2024)
// Hosted by USA, Canada, Mexico

export const GROUPS: Record<string, string[]> = {
  A: ['Estados Unidos', 'Panamá', 'Bolivia', 'Uruguay'],
  B: ['México', 'Jamaica', 'Venezuela', 'Ecuador'],
  C: ['Canadá', 'Honduras', 'Marruecos', 'Bélgica'],
  D: ['Brasil', 'Japón', 'Croacia', 'México'], // placeholder
  E: ['Argentina', 'Chile', 'Albania', 'Ucrania'],
  F: ['España', 'Serbia', 'Países Bajos', 'Australia'],
  G: ['Francia', 'Portugal', 'Colombia', 'Arabia Saudita'],
  H: ['Alemania', 'Corea del Sur', 'Costa Rica', 'Camerún'],
  I: ['Inglaterra', 'Senegal', 'Paraguay', 'Eslovenia'],
  J: ['Polonia', 'Turquía', 'Egipto', 'Costa de Marfil'],
  K: ['Irán', 'Qatar', 'Ghana', 'Suiza'],
  L: ['Kenia', 'Nueva Zelanda', 'Eslovaquia', 'Perú'],
}

export const STAGE_LABELS: Record<string, string> = {
  group: 'Fase de Grupos',
  round_of_32: 'Ronda de 32',
  round_of_16: 'Octavos de Final',
  quarterfinal: 'Cuartos de Final',
  semifinal: 'Semifinal',
  third_place: 'Tercer Puesto',
  final: 'Final',
}

export const FLAGS: Record<string, string> = {
  'Estados Unidos': '🇺🇸',
  'Panamá': '🇵🇦',
  'Bolivia': '🇧🇴',
  'Uruguay': '🇺🇾',
  'México': '🇲🇽',
  'Jamaica': '🇯🇲',
  'Venezuela': '🇻🇪',
  'Ecuador': '🇪🇨',
  'Canadá': '🇨🇦',
  'Honduras': '🇭🇳',
  'Marruecos': '🇲🇦',
  'Bélgica': '🇧🇪',
  'Brasil': '🇧🇷',
  'Japón': '🇯🇵',
  'Croacia': '🇭🇷',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Albania': '🇦🇱',
  'Ucrania': '🇺🇦',
  'España': '🇪🇸',
  'Serbia': '🇷🇸',
  'Países Bajos': '🇳🇱',
  'Australia': '🇦🇺',
  'Francia': '🇫🇷',
  'Portugal': '🇵🇹',
  'Colombia': '🇨🇴',
  'Arabia Saudita': '🇸🇦',
  'Alemania': '🇩🇪',
  'Corea del Sur': '🇰🇷',
  'Costa Rica': '🇨🇷',
  'Camerún': '🇨🇲',
  'Inglaterra': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Senegal': '🇸🇳',
  'Paraguay': '🇵🇾',
  'Eslovenia': '🇸🇮',
  'Polonia': '🇵🇱',
  'Turquía': '🇹🇷',
  'Egipto': '🇪🇬',
  'Costa de Marfil': '🇨🇮',
  'Irán': '🇮🇷',
  'Qatar': '🇶🇦',
  'Ghana': '🇬🇭',
  'Suiza': '🇨🇭',
  'Kenia': '🇰🇪',
  'Nueva Zelanda': '🇳🇿',
  'Eslovaquia': '🇸🇰',
  'Perú': '🇵🇪',
}
