// Grupos oficiales — Mundial 2026 (Sorteo: 5 dic 2024)
export const GROUPS: Record<string, string[]> = {
  A: ['México',          'Sudáfrica',      'Corea del Sur',  'Rep. Checa'],
  B: ['Canadá',          'Bosnia y Herz.', 'Qatar',          'Suiza'],
  C: ['Brasil',          'Marruecos',      'Haití',          'Escocia'],
  D: ['Estados Unidos',  'Paraguay',       'Australia',      'Turquía'],
  E: ['Alemania',        'Curazao',        'Costa de Marfil','Ecuador'],
  F: ['Países Bajos',    'Japón',          'Suecia',         'Túnez'],
  G: ['Bélgica',         'Egipto',         'Irán',           'Nueva Zelanda'],
  H: ['España',          'Cabo Verde',     'Arabia Saudita', 'Uruguay'],
  I: ['Francia',         'Senegal',        'Irak',           'Noruega'],
  J: ['Argentina',       'Argelia',        'Austria',        'Jordania'],
  K: ['Portugal',        'R.D. Congo',     'Uzbekistán',     'Colombia'],
  L: ['Inglaterra',      'Croacia',        'Ghana',          'Panamá'],
}

export const STAGE_LABELS: Record<string, string> = {
  group:        'Fase de Grupos',
  round_of_32:  'Ronda de 32',
  round_of_16:  'Octavos de Final',
  quarterfinal: 'Cuartos de Final',
  semifinal:    'Semifinal',
  third_place:  'Tercer Puesto',
  final:        'Final',
}

export const FLAGS: Record<string, string> = {
  'México':          '🇲🇽',
  'Sudáfrica':       '🇿🇦',
  'Corea del Sur':   '🇰🇷',
  'Rep. Checa':      '🇨🇿',
  'Canadá':          '🇨🇦',
  'Bosnia y Herz.':  '🇧🇦',
  'Qatar':           '🇶🇦',
  'Suiza':           '🇨🇭',
  'Brasil':          '🇧🇷',
  'Marruecos':       '🇲🇦',
  'Haití':           '🇭🇹',
  'Escocia':         '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  'Estados Unidos':  '🇺🇸',
  'Paraguay':        '🇵🇾',
  'Australia':       '🇦🇺',
  'Turquía':         '🇹🇷',
  'Alemania':        '🇩🇪',
  'Curazao':         '🇨🇼',
  'Costa de Marfil': '🇨🇮',
  'Ecuador':         '🇪🇨',
  'Países Bajos':    '🇳🇱',
  'Japón':           '🇯🇵',
  'Suecia':          '🇸🇪',
  'Túnez':           '🇹🇳',
  'Bélgica':         '🇧🇪',
  'Egipto':          '🇪🇬',
  'Irán':            '🇮🇷',
  'Nueva Zelanda':   '🇳🇿',
  'España':          '🇪🇸',
  'Cabo Verde':      '🇨🇻',
  'Arabia Saudita':  '🇸🇦',
  'Uruguay':         '🇺🇾',
  'Francia':         '🇫🇷',
  'Senegal':         '🇸🇳',
  'Irak':            '🇮🇶',
  'Noruega':         '🇳🇴',
  'Argentina':       '🇦🇷',
  'Argelia':         '🇩🇿',
  'Austria':         '🇦🇹',
  'Jordania':        '🇯🇴',
  'Portugal':        '🇵🇹',
  'R.D. Congo':      '🇨🇩',
  'Uzbekistán':      '🇺🇿',
  'Colombia':        '🇨🇴',
  'Inglaterra':      '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  'Croacia':         '🇭🇷',
  'Ghana':           '🇬🇭',
  'Panamá':          '🇵🇦',
}
